version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: make image

      - run: make test

      - run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          make push-image
