name: Build

on: push

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make image

      - name: Test
        run: make test

      - name: Lint
        run: make lint

      - name: Push
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        if: github.ref == 'refs/heads/master'
        run: make push-image
